export const api = [
  {
    customers: [
      {
        name: "Márcio Braga",
        email: "marcio.braga@minhaempresa.com.br",
        phone: "(21) 98987-7650",
        status: "paying",
        subscription_amount: 250.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/men/75.jpg",
      },
      {
        name: "Felipe Cardoso",
        email: "felipe.cardoso@minhaempresa.com.br",
        phone: "(21) 98987-7651",
        status: "paying",
        subscription_amount: 250.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/men/74.jpg",
      },
      {
        name: "Maria Silva",
        email: "maria.silva@minhaempresa.com.br",
        phone: "(21) 98987-7652",
        status: "overdue",
        subscription_amount: 750.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/women/75.jpg",
      },
      {
        name: "Eduardo Lopes",
        email: "eduardo.lopes@minhaempresa.com.br",
        phone: "(21) 98987-7653",
        status: "overdue",
        subscription_amount: 250.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/men/73.jpg",
      },
      {
        name: "Nathalia Amaral",
        email: "nathalia.amaral@minhaempresa.com.br",
        phone: "(21) 98987-7654",
        status: "paying",
        subscription_amount: 150.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/women/74.jpg",
      },
      {
        name: "Maria Fernanda",
        email: "maria.fernanda@minhaempresa.com.br",
        phone: "(21) 98987-7655",
        status: "overdue",
        subscription_amount: 250.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/women/73.jpg",
      },
      {
        name: "Roberto Duarte",
        email: "roberto.duarte@minhaempresa.com.br",
        phone: "(21) 98987-7656",
        status: "overdue",
        subscription_amount: 950.99,
        profile_url: "https://randomuser.me/api/portraits/thumb/men/72.jpg",
      },
    ],
  },
];
